# Generated by Django 5.0.3 on 2024-03-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0005_orders_last_name_alter_orders_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(default=1),
        ),
    ]
