# Generated by Django 5.0.3 on 2024-03-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0007_alter_orders_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.TextField(choices=[('ORDER_PROCESSED', 'ORDER_PROCESSED'), ('ORDER_DELIVERD', 'ORDER_DELIVERD'), ('ORDER_REJECTED', 'ORDER_REJECTED')], default=0),
        ),
    ]
