# Generated by Django 5.0.3 on 2024-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0008_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='location',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='u_mobile',
            field=models.IntegerField(null=True),
        ),
    ]
