# Generated by Django 5.0.3 on 2024-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0009_user_reg_location_user_reg_u_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='dob',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='gender',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
