# Generated by Django 5.0.3 on 2024-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0010_user_reg_dob_user_reg_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
