# Generated by Django 5.0.3 on 2024-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0012_product_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_rating',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
