# Generated by Django 5.0.3 on 2024-04-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0013_feedback_user_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.TextField(max_length=500)),
                ('user_rating', models.IntegerField(max_length=5, null=True)),
                ('review_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UrbanVox_app.user_reg')),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
