# Generated by Django 5.0.3 on 2024-04-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0015_alter_review_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_date',
        ),
    ]
