# Generated by Django 5.0.3 on 2024-04-08 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0018_alter_review_user_rating_alter_review_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UrbanVox_app.product'),
        ),
    ]
