# Generated by Django 5.0.3 on 2024-04-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0020_review_review_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_rating',
            field=models.IntegerField(default=0),
        ),
    ]
