# Generated by Django 5.0.2 on 2024-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0021_alter_review_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_amount',
            field=models.IntegerField(null=True),
        ),
    ]
