# Generated by Django 5.0.3 on 2024-05-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0023_alter_orders_order_amount_alter_orders_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mobile_num',
            field=models.IntegerField(default=9090909090),
        ),
    ]
