# Generated by Django 5.0.3 on 2024-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanVox_app', '0026_alter_orders_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mobile_num',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
